"""initial schema

Revision ID: 04481fcb83c8
Revises: 
Create Date: 2026-01-05 17:37:02.377511

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '04481fcb83c8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('matches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.String(length=32), nullable=False),
    sa.Column('regional', sa.String(length=10), nullable=False),
    sa.Column('platform', sa.String(length=10), nullable=False),
    sa.Column('game_start_ms', sa.Integer(), nullable=True),
    sa.Column('queue_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('match_id', name='uq_matches_match_id')
    )
    op.create_index(op.f('ix_matches_match_id'), 'matches', ['match_id'], unique=False)
    op.create_table('players',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('region', sa.String(length=10), nullable=False),
    sa.Column('summoner_name', sa.String(length=50), nullable=True),
    sa.Column('puuid', sa.String(length=90), nullable=False),
    sa.Column('summoner_id', sa.String(length=90), nullable=True),
    sa.Column('last_updated', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_players_id'), 'players', ['id'], unique=False)
    op.create_index(op.f('ix_players_puuid'), 'players', ['puuid'], unique=True)
    op.create_index(op.f('ix_players_summoner_name'), 'players', ['summoner_name'], unique=False)
    op.create_table('player_riot_ids',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('puuid', sa.String(length=90), nullable=False),
    sa.Column('game_name', sa.String(length=40), nullable=False),
    sa.Column('tag_line', sa.String(length=10), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['puuid'], ['players.puuid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('puuid', 'game_name', 'tag_line', name='uq_player_riot_id')
    )
    op.create_index(op.f('ix_player_riot_ids_game_name'), 'player_riot_ids', ['game_name'], unique=False)
    op.create_index(op.f('ix_player_riot_ids_puuid'), 'player_riot_ids', ['puuid'], unique=False)
    op.create_index(op.f('ix_player_riot_ids_tag_line'), 'player_riot_ids', ['tag_line'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_player_riot_ids_tag_line'), table_name='player_riot_ids')
    op.drop_index(op.f('ix_player_riot_ids_puuid'), table_name='player_riot_ids')
    op.drop_index(op.f('ix_player_riot_ids_game_name'), table_name='player_riot_ids')
    op.drop_table('player_riot_ids')
    op.drop_index(op.f('ix_players_summoner_name'), table_name='players')
    op.drop_index(op.f('ix_players_puuid'), table_name='players')
    op.drop_index(op.f('ix_players_id'), table_name='players')
    op.drop_table('players')
    op.drop_index(op.f('ix_matches_match_id'), table_name='matches')
    op.drop_table('matches')
    # ### end Alembic commands ###
