"""drop fk match_participants puuid

Revision ID: 1a5aff7e8398
Revises: 079732f58e5b
Create Date: 2026-01-05 19:56:42.369032

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a5aff7e8398'
down_revision: Union[str, Sequence[str], None] = '079732f58e5b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('match_participants_puuid_fkey'), 'match_participants', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(op.f('match_participants_puuid_fkey'), 'match_participants', 'players', ['puuid'], ['puuid'], ondelete='CASCADE')
    # ### end Alembic commands ###
