"""add player_riot_ids

Revision ID: 6e2f3a5dcd0f
Revises: 04481fcb83c8
Create Date: 2026-01-05 18:50:14.408251

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e2f3a5dcd0f'
down_revision: Union[str, Sequence[str], None] = '04481fcb83c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
